"""schema inicial completo

Revision ID: 80c013aa867b
Revises: 
Create Date: 2026-04-20 15:58:02.484949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c013aa867b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('fantasia', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('MATRIZ', 'FILIAL', name='tipoempresa'), nullable=True),
    sa.Column('porte', sa.String(length=100), nullable=True),
    sa.Column('natureza_juridica', sa.String(length=100), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('abertura', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=True),
    sa.Column('data_situacao', sa.Date(), nullable=True),
    sa.Column('motivo_situacao', sa.String(length=200), nullable=True),
    sa.Column('situacao_especial', sa.String(length=200), nullable=True),
    sa.Column('data_situacao_especial', sa.Date(), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=100), nullable=True),
    sa.Column('simples_optante', sa.Boolean(), nullable=True),
    sa.Column('simples_data_opcao', sa.Date(), nullable=True),
    sa.Column('simples_data_exclusao', sa.Date(), nullable=True),
    sa.Column('simei_optante', sa.Boolean(), nullable=True),
    sa.Column('ultima_atualizacao_api', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_table('tipos_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('atividades_empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_atividades_codigo', 'atividades_empresa', ['codigo'], unique=False)
    op.create_index(op.f('ix_atividades_empresa_empresa_id'), 'atividades_empresa', ['empresa_id'], unique=False)
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_empresa_id'), 'contatos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_contatos_telefone'), 'contatos', ['telefone'], unique=True)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_produto_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('preco_tabela', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipos_produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_produtos_tipo_produto_id'), 'produtos', ['tipo_produto_id'], unique=False)
    op.create_table('socios_empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('qualificacao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_socios_nome', 'socios_empresa', ['nome'], unique=False)
    op.create_index(op.f('ix_socios_empresa_empresa_id'), 'socios_empresa', ['empresa_id'], unique=False)
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('novo', 'em_contato', 'aguardando_orcamento', 'orcamento_enviado', 'em_negociacao', 'fechado_venda', 'fechado_perda', 'arquivado', name='statusnegociacao'), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negociacoes_contato_id'), 'negociacoes', ['contato_id'], unique=False)
    op.create_index(op.f('ix_negociacoes_empresa_id'), 'negociacoes', ['empresa_id'], unique=False)
    op.create_table('itens_negociacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negociacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo_produto_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negociacao_id'], ['negociacoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipos_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_negociacao_negociacao_id'), 'itens_negociacao', ['negociacao_id'], unique=False)
    op.create_index(op.f('ix_itens_negociacao_produto_id'), 'itens_negociacao', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_negociacao_tipo_produto_id'), 'itens_negociacao', ['tipo_produto_id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('origem', sa.Enum('user', 'system', name='origemmensagem'), nullable=False),
    sa.Column('message_sid', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.Column('negociacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['negociacao_id'], ['negociacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid')
    )
    op.create_index('idx_mensagens_contato', 'mensagens', ['contato_id'], unique=False)
    op.create_index('idx_mensagens_negociacao', 'mensagens', ['negociacao_id'], unique=False)
    op.create_index('idx_mensagens_telefone_timestamp', 'mensagens', ['telefone', 'timestamp'], unique=False)
    op.create_index(op.f('ix_mensagens_contato_id'), 'mensagens', ['contato_id'], unique=False)
    op.create_index(op.f('ix_mensagens_negociacao_id'), 'mensagens', ['negociacao_id'], unique=False)
    op.create_index(op.f('ix_mensagens_telefone'), 'mensagens', ['telefone'], unique=False)
    op.create_table('negociacao_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negociacao_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('pendente', sa.Boolean(), nullable=False),
    sa.Column('origem', sa.Enum('user', 'inferido', 'sistema', 'atendente', name='origeminfo'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negociacao_id'], ['negociacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_negociacao_info_chave', 'negociacao_infos', ['negociacao_id', 'chave'], unique=True)
    op.create_index(op.f('ix_negociacao_infos_negociacao_id'), 'negociacao_infos', ['negociacao_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negociacao_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('em_elaboracao', 'pendente_aprovacao', 'enviado_cliente', 'aprovado', 'reprovado', 'expirado', name='statusorcamento'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negociacao_id'], ['negociacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_orcamentos_negociacao_id'), 'orcamentos', ['negociacao_id'], unique=False)
    op.create_table('itens_orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_orcamento_orcamento_id'), 'itens_orcamento', ['orcamento_id'], unique=False)
    op.create_index(op.f('ix_itens_orcamento_produto_id'), 'itens_orcamento', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_orcamento_produto_id'), table_name='itens_orcamento')
    op.drop_index(op.f('ix_itens_orcamento_orcamento_id'), table_name='itens_orcamento')
    op.drop_table('itens_orcamento')
    op.drop_index(op.f('ix_orcamentos_negociacao_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_negociacao_infos_negociacao_id'), table_name='negociacao_infos')
    op.drop_index('idx_negociacao_info_chave', table_name='negociacao_infos')
    op.drop_table('negociacao_infos')
    op.drop_index(op.f('ix_mensagens_telefone'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_negociacao_id'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_contato_id'), table_name='mensagens')
    op.drop_index('idx_mensagens_telefone_timestamp', table_name='mensagens')
    op.drop_index('idx_mensagens_negociacao', table_name='mensagens')
    op.drop_index('idx_mensagens_contato', table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_itens_negociacao_tipo_produto_id'), table_name='itens_negociacao')
    op.drop_index(op.f('ix_itens_negociacao_produto_id'), table_name='itens_negociacao')
    op.drop_index(op.f('ix_itens_negociacao_negociacao_id'), table_name='itens_negociacao')
    op.drop_table('itens_negociacao')
    op.drop_index(op.f('ix_negociacoes_empresa_id'), table_name='negociacoes')
    op.drop_index(op.f('ix_negociacoes_contato_id'), table_name='negociacoes')
    op.drop_table('negociacoes')
    op.drop_index(op.f('ix_socios_empresa_empresa_id'), table_name='socios_empresa')
    op.drop_index('idx_socios_nome', table_name='socios_empresa')
    op.drop_table('socios_empresa')
    op.drop_index(op.f('ix_produtos_tipo_produto_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_contatos_telefone'), table_name='contatos')
    op.drop_index(op.f('ix_contatos_empresa_id'), table_name='contatos')
    op.drop_table('contatos')
    op.drop_index(op.f('ix_atividades_empresa_empresa_id'), table_name='atividades_empresa')
    op.drop_index('idx_atividades_codigo', table_name='atividades_empresa')
    op.drop_table('atividades_empresa')
    op.drop_table('tipos_produto')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
