"""adiciona_pares_qa

Revision ID: 3699280dbfe7
Revises: 2026043002
Create Date: 2026-05-10 10:55:59.237553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import UserDefinedType


class Vector(UserDefinedType):
    """Tipo pgvector usado na migration."""

    cache_ok = True

    def __init__(self, dimensions: int):
        self.dimensions = dimensions

    def get_col_spec(self, **kw) -> str:
        return f"vector({self.dimensions})"

# revision identifiers, used by Alembic.
revision: str = '3699280dbfe7'
down_revision: Union[str, None] = '2026043002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pares_qa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('contexto', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('criado_por', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_externo')
    )
    op.create_index('idx_pares_qa_aprovado_ativo', 'pares_qa', ['aprovado', 'ativo'], unique=False)
    op.create_index('idx_pares_qa_contexto_ativo', 'pares_qa', ['contexto', 'ativo'], unique=False)
    op.drop_index('idx_documentos_conhecimento_embedding_cosine', table_name='documentos_conhecimento', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_documentos_conhecimento_id_documento_origem', table_name='documentos_conhecimento')
    op.drop_index('idx_documentos_conhecimento_id_fonte', table_name='documentos_conhecimento')
    op.drop_index('idx_documentos_conhecimento_metadata_gin', table_name='documentos_conhecimento', postgresql_using='gin')
    op.create_index(op.f('ix_documentos_conhecimento_ativo'), 'documentos_conhecimento', ['ativo'], unique=False)
    op.create_index(op.f('ix_documentos_conhecimento_conteudo_hash'), 'documentos_conhecimento', ['conteudo_hash'], unique=False)
    op.create_index(op.f('ix_documentos_conhecimento_id_documento_origem'), 'documentos_conhecimento', ['id_documento_origem'], unique=False)
    op.create_index(op.f('ix_documentos_conhecimento_id_fonte'), 'documentos_conhecimento', ['id_fonte'], unique=False)
    op.create_index(op.f('ix_documentos_conhecimento_tipo'), 'documentos_conhecimento', ['tipo'], unique=False)
    op.create_index(op.f('ix_documentos_conhecimento_titulo'), 'documentos_conhecimento', ['titulo'], unique=False)
    op.drop_constraint('fk_mensagens_aprovador_users', 'mensagens', type_='foreignkey')
    op.create_foreign_key(None, 'mensagens', 'users', ['aprovador_id'], ['id'])
    op.drop_index('idx_reports_mensagem_id', table_name='reports_problema')
    op.drop_index('ix_reports_problema_categoria', table_name='reports_problema')
    op.create_index(op.f('ix_reports_problema_mensagem_id'), 'reports_problema', ['mensagem_id'], unique=False)
    op.drop_column('reports_problema', 'resolvido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports_problema', sa.Column('resolvido', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reports_problema_mensagem_id'), table_name='reports_problema')
    op.create_index('ix_reports_problema_categoria', 'reports_problema', ['categoria'], unique=False)
    op.create_index('idx_reports_mensagem_id', 'reports_problema', ['mensagem_id'], unique=False)
    op.drop_constraint(None, 'mensagens', type_='foreignkey')
    op.create_foreign_key('fk_mensagens_aprovador_users', 'mensagens', 'users', ['aprovador_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documentos_conhecimento_titulo'), table_name='documentos_conhecimento')
    op.drop_index(op.f('ix_documentos_conhecimento_tipo'), table_name='documentos_conhecimento')
    op.drop_index(op.f('ix_documentos_conhecimento_id_fonte'), table_name='documentos_conhecimento')
    op.drop_index(op.f('ix_documentos_conhecimento_id_documento_origem'), table_name='documentos_conhecimento')
    op.drop_index(op.f('ix_documentos_conhecimento_conteudo_hash'), table_name='documentos_conhecimento')
    op.drop_index(op.f('ix_documentos_conhecimento_ativo'), table_name='documentos_conhecimento')
    op.create_index('idx_documentos_conhecimento_metadata_gin', 'documentos_conhecimento', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documentos_conhecimento_id_fonte', 'documentos_conhecimento', ['id_fonte'], unique=False)
    op.create_index('idx_documentos_conhecimento_id_documento_origem', 'documentos_conhecimento', ['id_documento_origem'], unique=False)
    op.create_index('idx_documentos_conhecimento_embedding_cosine', 'documentos_conhecimento', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_pares_qa_contexto_ativo', table_name='pares_qa')
    op.drop_index('idx_pares_qa_aprovado_ativo', table_name='pares_qa')
    op.drop_table('pares_qa')
    # ### end Alembic commands ###
